name: pkgcheck

on:
  push:
    branches: [stream]
  pull_request:
    branches: [stream]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
      with:
        args: --keywords=-NonsolvableDepsInStable,-UnknownRestrict --profiles=default/linux/amd64/23.0/llvm,default/linux/amd64/23.0/desktop
