name: pkgcheck

on:
  push:
    branches: [stream]
  pull_request:
    branches: [stream]

jobs:
  build:
    runs-on: [self-hosted, Ephemerality]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
      with:
        args: --keywords=-NonsolvableDepsInStable
